name: test

on: [pull_request]

jobs:
  test-workers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.11']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        working-directory: app/workers
        run: poetry install --no-interaction --no-root

      - name: Test with pytest Poetry
        working-directory: app/workers
        run: |
          poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=sources test | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: app/workers/pytest-coverage.txt
          junitxml-path: app/workers/pytest.xml

  test-django:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          python-version: ['3.8', '3.11']
          django-version: [ '3.1.14', '4.2']

      services:
        postgres:
          image: postgres
          env:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: test
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432

      steps:
        - uses: actions/checkout@v3

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install Poetry
          uses: snok/install-poetry@v1

        - name: Load cached venv
          id: cached-poetry-dependencies
          uses: actions/cache@v3
          with:
            path: .venv
            key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

        - name: Install dependencies
          if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
          working-directory: app/api
          run: poetry install --no-interaction --no-root

        - name: Install django ${{ matrix.django-version }}
          working-directory: app/api
          run: |
            poetry run python -m venv .venv
            source .venv/bin/activate
            pip install "Django==${{ matrix.django-version }}"

        - name: Test with Django
          env:
            SECRET_KEY: 'test'
            ALLOWED_HOSTS: "['localhost']"
            COCONNECT_DB_ENGINE: "django.db.backends.postgresql"
            COCONNECT_DB_HOST: "localhost"
            COCONNECT_DB_NAME: "test"
            COCONNECT_DB_PASSWORD: "postgres"
            COCONNECT_DB_PORT: "5432"
            COCONNECT_DB_USER: "postgres"
          working-directory: app/api
          run: |
            poetry run pytest
